openapi: 3.0.0
info:
  version: '2021-11-29'
  x-release: v4
  title: AWS IoT TwinMaker Pricingplan Workspaces List API
  description: IoT TwinMaker is a service with which you can build operational digital twins of physical systems. IoT TwinMaker overlays measurements and analysis from real-world sensors, cameras, and enterprise applications so you can create data visualizations to monitor your physical factory, building, or industrial plant. You can use this real-world data to monitor operations and diagnose and repair errors.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: iottwinmaker
  x-aws-signingName: iottwinmaker
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/iottwinmaker-2021-11-29.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://iottwinmaker.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS IoT TwinMaker multi-region endpoint
- url: https://iottwinmaker.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS IoT TwinMaker multi-region endpoint
- url: http://iottwinmaker.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS IoT TwinMaker endpoint for China (Beijing) and China (Ningxia)
- url: https://iottwinmaker.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS IoT TwinMaker endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Workspaces List
paths:
  /workspaces-list:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListWorkspaces
      description: Retrieves information about workspaces in the current account.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListWorkspacesResponse'
        '480':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
        '481':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
        '482':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
        '483':
          description: ServiceQuotaExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceQuotaExceededException'
      parameters:
      - name: maxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: nextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                maxResults:
                  description: '<p>The maximum number of results to return at one time. The default is 25.</p> <p>Valid Range: Minimum value of 1. Maximum value of 250.</p>'
                  type: integer
                  minimum: 0
                  maximum: 200
                nextToken:
                  description: The string that specifies the next page of results.
                  type: string
                  pattern: .*
                  minLength: 0
                  maxLength: 17880
      summary: Amazon IoT TwinMaker List Workspaces
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Workspaces List
components:
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
  schemas:
    ListWorkspacesResponse:
      type: object
      properties:
        workspaceSummaries:
          allOf:
          - $ref: '#/components/schemas/WorkspaceSummaries'
          - description: A list of objects that contain information about the workspaces.
        nextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: The string that specifies the next page of results.
    WorkspaceSummaries:
      type: array
      items:
        $ref: '#/components/schemas/WorkspaceSummary'
    Description:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 2048
    TwinMakerArn:
      type: string
      pattern: arn:((aws)|(aws-cn)|(aws-us-gov)):iottwinmaker:[a-z0-9-]+:[0-9]{12}:[\/a-zA-Z0-9_\-\.:]+
      minLength: 20
      maxLength: 2048
    ServiceQuotaExceededException: {}
    NextToken:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 17880
    Id:
      type: string
      pattern: '[a-zA-Z_0-9][a-zA-Z_\-0-9]*[a-zA-Z0-9]+'
      minLength: 1
      maxLength: 128
    WorkspaceSummary:
      type: object
      required:
      - workspaceId
      - arn
      - creationDateTime
      - updateDateTime
      properties:
        workspaceId:
          allOf:
          - $ref: '#/components/schemas/Id'
          - description: The ID of the workspace.
        arn:
          allOf:
          - $ref: '#/components/schemas/TwinMakerArn'
          - description: The ARN of the workspace.
        description:
          allOf:
          - $ref: '#/components/schemas/Description'
          - description: The description of the workspace.
        creationDateTime:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The date and time when the workspace was created.
        updateDateTime:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The date and time when the workspace was last updated.
      description: An object that contains information about a workspace.
    ThrottlingException: {}
    ValidationException: {}
    Timestamp:
      type: string
      description: supports epoch seconds value
      format: date-time
    InternalServerException: {}
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/iottwinmaker/
x-hasEquivalentPaths: true
